VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Emplyee"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' under consideration
Option Explicit

' ƒƒ“ƒo•Ï”
Public Name As String
Public EmplyeeId As String
Public Department As String
Public Team As String
Public IsOnLoan As String
Public NgCount As String

