name: uniitest

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install httpretty
        pip install parse
        pip install pylint==2.15.10
    - name: Run test with uniitest
      working-directory: ./sorachat
      run: |
        python -m unittest discover tests
